#!/bin/bash
echo Das ist eine ausführbare Bash File
x="this is a string stored in a variable"

y=6.4
z=3
a=$(python -c "print $y+$z")

if [ $y =  5 ]; then 
	echo a ist 5
else 
	echo a ist nicht 5
fi

echo $a 
